### ISSUE TITLE
0.1.0

### ISSUE THREAD

**Issue by Briancbn** [Briancbn/ros_vim_autocomplete#1]
## TODOs
- [x] ROS 2 support
- [x] Custom ycm config in `.vimrc` to avoid common errors
- [x] Custom color scheme for ycm error and warning highlight
- [x] YCM Installation instruction
- [x] ROS YCM configuration setup and usage documentation
- [ ] Setup test cases
- [ ] Unit test for key functions
- [x] Setup Workflow for multiple OS

Optional:
- [ ] Support Windows
- [ ] Better python checker
- [x] Lint?
- [x] Tabnine
